---
hide_body: false
fields:
- name: date
  label: Date
  type: field_group
  hidden: false
  default: {}
- type: text
  name: fill_this_form
  label: Email
  description: Email
  hidden: false
  config:
    required: true
